name: 🚀 Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v4

      # 2. Install Dependencies (Conditional)
      - name: 🔨 Install Dependencies
        if: ${{ github.event.before != '0000000000000000000000000000000000000000' }}
        run: |
          git diff --name-only HEAD^ HEAD | grep -qE '(composer\.json|composer\.lock)' && composer install --no-dev --optimize-autoloader || echo "No dependencies updated"

      # 3. Find Changed Files
      - name: 🔍 Find Changed Files
        id: changes
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch --unshallow || true
          fi
          if git rev-parse HEAD^ > /dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD > changed_files.txt
          else
            echo "Initial commit detected. Including all files." > changed_files.txt
            git ls-files >> changed_files.txt
          fi
          cat changed_files.txt

      # 4. Upload Incrementally via FTP
      - name: 📂 Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Direktori lokal Laravel
          server-dir: / # Direktori di server
          exclude: |
            **/.env*
            **/.git/**
            **/storage/**
            **/database/**
            **/config/**
            **/test/**
            **/bootstrap/**
            **/lang/**
            **/public/**
            **/app/console/**
            **/app/exceptions/**
            **/app/http/middleware/**
            **/app/http/requests/**
            **/app/http/kernel.php
            **/app/notifications/**
            **/app/policies/**
            **/app/providers/**
            **/app/view/**
            **/resources/css/**
            **/resources/js/**
            **/resources/views/components/**
          dangerous-clean-slate: false # Set to true if you want to remove files not in repo
          concurrency: 1 # Limit connections to avoid server overload
          timeout: 60000 # Extend timeout if needed
